/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import controlador.ejercicio1.Ejercicio1Controller;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import vista.ejemplo1.modeloTabla.ModeloTabla1;


public class Frm_Ejemplo1 extends javax.swing.JDialog {

    private Ejercicio1Controller controller;
    private ModeloTabla1 mt = new ModeloTabla1();

    /**
     * Creates new form Frm_Ejemplo1
     */
    public Frm_Ejemplo1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cbxInicio.removeAllItems();
        cbxFinal.removeAllItems();
    }

    private void cargarTabla() {
        if (controller != null) {
            mt.setGrafoD(controller.getGrafoD());
            tblTabla.setModel(mt);
            mt.fireTableStructureChanged();
            tblTabla.updateUI();
        } else {
            DefaultTableModel modelo = new DefaultTableModel(1, 1);
            tblTabla.setModel(modelo);
            tblTabla.updateUI();
        }
    }

    private void agregar() {
        if (controller != null) {
            Integer inicio = Integer.parseInt(cbxInicio.getSelectedItem().toString());
            Integer fin = Integer.parseInt(cbxFinal.getSelectedItem().toString());
            if (inicio.intValue() == fin.intValue()) {
                JOptionPane.showMessageDialog(null, "No se pude agregar con el mismo vertice", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                controller.getGrafoD().insertarArista(inicio, fin);
                cargarTabla();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Genere el grafo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void crearGrafo() {
        Integer aux = Integer.parseInt(cbxNroV.getSelectedItem().toString());
        controller = new Ejercicio1Controller(aux);
        cbxInicio.removeAllItems();
        cbxFinal.removeAllItems();
        for (int i = 0; i < aux; i++) {
            cbxInicio.addItem(String.valueOf(i + 1));
            cbxFinal.addItem(String.valueOf(i + 1));
        }
        cargarTabla();
    }

    private void mostrarGrafo() {
        if (controller != null) {
            new Frm_PresentarGrafo(null, true, controller).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Genere el grafo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxNroV = new javax.swing.JComboBox<>();
        btnGenerar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbxInicio = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbxFinal = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();
        btnVer = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtVerFinalNombre = new javax.swing.JTextField();
        txtVerInNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Generar Grafo"));

        jLabel1.setText("Nro de vertices");

        cbxNroV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4", "5", "6", "7", "8", "9" }));

        btnGenerar.setText("GENERAR");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(cbxNroV, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxNroV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerar))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 660, 100);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Lista de Adyacencia"));
        jPanel2.setLayout(null);

        jLabel2.setText("Nombre:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(320, 50, 41, 14);

        jPanel2.add(cbxInicio);
        cbxInicio.setBounds(110, 20, 180, 22);

        jLabel3.setText("Nombre:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 50, 41, 14);

        jPanel2.add(cbxFinal);
        cbxFinal.setBounds(420, 20, 180, 22);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregar);
        btnAgregar.setBounds(620, 10, 71, 23);

        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTabla);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 80, 690, 140);

        btnVer.setText("Ver");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        jPanel2.add(btnVer);
        btnVer.setBounds(620, 50, 90, 23);

        jLabel4.setText("Vertice Inicial: ");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(19, 29, 70, 14);

        jLabel5.setText("Vertice Final: ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(320, 20, 65, 14);
        jPanel2.add(txtVerFinalNombre);
        txtVerFinalNombre.setBounds(420, 50, 180, 20);
        jPanel2.add(txtVerInNombre);
        txtVerInNombre.setBounds(110, 50, 180, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 140, 730, 240);

        setBounds(0, 0, 783, 427);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        crearGrafo();
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        agregar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        mostrarGrafo();
    }//GEN-LAST:event_btnVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Ejemplo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Ejemplo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Ejemplo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Ejemplo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frm_Ejemplo1 dialog = new Frm_Ejemplo1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnVer;
    private javax.swing.JComboBox<String> cbxFinal;
    private javax.swing.JComboBox<String> cbxInicio;
    private javax.swing.JComboBox<String> cbxNroV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTabla;
    private javax.swing.JTextField txtVerFinalNombre;
    private javax.swing.JTextField txtVerInNombre;
    // End of variables declaration//GEN-END:variables
}
